/*
 * certificates.js - certificate cards + preview dialog.
 * Data comes from window.__CERTS (js/assets-data.js, generated by tools/build_assets.py).
 * Click a card -> larger preview of the PDF's first page with a "Unduh PDF" button.
 */
(function () {
  var $ = function (i) {
    return document.getElementById(i);
  };
  var C = window.__CERTS || [],
    g = document.getElementById('ct');
  if (!g || !C.length) return;
  g.innerHTML = C.map(function (c, i) {
    return (
      '<button type="button" class="c cert" data-i="' +
      i +
      '"><span class="cth"><img alt="Pratinjau ' +
      c.t +
      '" src="data:image/jpeg;base64,' +
      c.img +
      '"><span class="cbd">PDF</span></span><span class="k">' +
      c.s +
      ' · ' +
      c.y +
      '</span><h3>' +
      c.t +
      '</h3><p>Klik untuk pratinjau &amp; unduh</p></button>'
    );
  }).join('');
  var m = document.createElement('div');
  m.id = 'cm';
  m.hidden = true;
  m.setAttribute('role', 'dialog');
  m.setAttribute('aria-modal', 'true');
  m.setAttribute('aria-labelledby', 'cmt');
  m.innerHTML =
    '<div class="cmp"><div class="cmh"><div><b id="cmt"></b><span id="cms"></span></div><div class="cmb"><button type="button" class="btn p" id="cmd">Unduh PDF</button><button type="button" class="btn" id="cmx">Tutup</button></div></div><div class="cmi"><img id="cmimg" alt=""></div><p id="cmm" class="mut"></p></div>';
  document.body.appendChild(m);
  var cur = null,
    from = null;
  // Show the preview dialog for certificate i.
  function open(i, el) {
    cur = C[i];
    from = el;
    $('cmt').textContent = cur.t;
    $('cms').textContent = cur.s + ' · ' + cur.y;
    $('cmimg').src = 'data:image/jpeg;base64,' + cur.img;
    $('cmimg').alt = 'Pratinjau ' + cur.t;
    $('cmm').textContent = '';
    m.hidden = false;
    document.documentElement.style.overflow = 'hidden';
    $('cmx').focus();
  }
  function close() {
    m.hidden = true;
    document.documentElement.style.overflow = '';
    if (from) from.focus();
  }
  // base64 PDF -> Blob (used for downloading).
  function blob(b) {
    var s = atob(b),
      u = new Uint8Array(s.length);
    for (var i = 0; i < s.length; i++) u[i] = s.charCodeAt(i);
    return new Blob([u], { type: 'application/pdf' });
  }
  g.addEventListener('click', function (e) {
    var b = e.target.closest('.cert');
    if (b) open(+b.dataset.i, b);
  });
  m.addEventListener('click', function (e) {
    if (e.target === m) close();
  });
  $('cmx').onclick = close;
  document.addEventListener('keydown', function (e) {
    if (m.hidden) return;
    if (e.key === 'Escape') close();
    if (e.key === 'Tab') {
      var a = [$('cmd'), $('cmx')],
        i = a.indexOf(document.activeElement);
      e.preventDefault();
      a[(i + (e.shiftKey ? -1 : 1) + 2) % 2].focus();
    }
  });
  $('cmd').onclick = async function () {
    var c = cur,
      b = blob(c.pdf),
      n = $('cmm');
    try {
      var dl = window.claude && (await window.claude.use('downloads'));
      if (dl) {
        await dl.save({ filename: c.fn, data: b });
        n.textContent = 'Unduhan dimulai.';
        return;
      }
    } catch (e) {
      if (e && e.code === 'declined') return;
    }
    var u = URL.createObjectURL(b),
      a = document.createElement('a');
    a.href = u;
    a.download = c.fn;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(function () {
      URL.revokeObjectURL(u);
    }, 4000);
    n.textContent = 'Jika unduhan tidak mulai, buka halaman ini di tab baru.';
  };
})();
