#!/usr/bin/env python3
"""Generate js/assets-data.js from the files in assets/.

The site embeds its assets as base64 so index.html also works when opened
directly from disk (no local server needed). Run this script again after you
add or replace a certificate or a project screenshot:

    python3 tools/build_assets.py
"""
import base64
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"

# (file name without extension, title, issuer, year, download file name)
# Each entry needs assets/certificates/<name>.pdf and <name>.jpg (preview of page 1).
CERTIFICATES = [
    ("revou-intro-to-software-engineering", "Intro to Software Engineering",
     "RevoU", 2025, "Sertifikat-RevoU-Intro-to-Software-Engineering.pdf"),
    ("mathworks-matlab", "MATLAB 入门之旅",
     "MathWorks", 2025, "Sertifikat-MathWorks-MATLAB.pdf"),
    ("coursera-canva-3d-effect", "Graphic Design: Pop Your LinkedIn with 3D Effect Using Canva",
     "Coursera", 2026, "Sertifikat-Coursera-Canva-3D-Effect.pdf"),
]

# Project screenshots, keyed by the id used in js/projects.js.
PROJECTS = {
    "sig": "projects/sig-tps.jpg",
    "portfolio": "projects/portfolio.jpg",
}


def b64(relative_path):
    return base64.b64encode((ASSETS / relative_path).read_bytes()).decode()


def main():
    certificates = [
        {
            "t": title, "s": issuer, "y": year, "fn": filename,
            "img": b64(f"certificates/{name}.jpg"),
            "pdf": b64(f"certificates/{name}.pdf"),
        }
        for name, title, issuer, year, filename in CERTIFICATES
    ]
    projects = {key: b64(path) for key, path in PROJECTS.items()}

    lines = [
        "// GENERATED by tools/build_assets.py - do not edit by hand.",
        f'window.__GLB = "{b64("kartu.glb")}"; // 3D card model',
        f'window.__BAND = "{b64("bandd.png")}"; // lanyard texture',
        f'window.__TEX = "{b64("card-back.png")}"; // card back texture',
        f"window.__CERTS = {json.dumps(certificates, ensure_ascii=False)};",
        f"window.__PROJ = {json.dumps(projects)};",
    ]
    out = ROOT / "js" / "assets-data.js"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out.relative_to(ROOT)}: {out.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
